


#' Location-Scale basis spline regression
#'
#' @description
#'
#' The Location-scale bspline regression model enables flexible non-parametric
#' modeling of the mean and of the standard deviation. It is only possible to
#' model one predictor variable. To control the smoothness of the model a
#' penalization term is applied
#'
#' @param m  A LMLS object generated by a call to the lmls function. Only one
#'           predictor variable can be used and a predictor variable for the
#'           scale parameter needs to be defined. Also light = True needs to be
#'           set.
#'
#' @param kn kn vector of integers 1. specifying number of knots for location
#'           2. specifying number of knots for scale
#'
#' @param order vector of integers 1. specifying order of spline for location
#'              2. specifying order of spline for scale
#'
#' @param p_order vector of integers 1. specifying order of spline for location
#'                2. specifying order of spline for scale
#'
#' @param smooth vector of positive floats specifying strength of penalization
#'               1. for location parameters (1/tau)
#'               2. for scale parameters (1/epsilon)
#'
#' @return a LMLS object with estimations for the location and scale
#'         coefficients.
#' @export

spline = function(m, kn, order, p_order, smooth)
{
  m = initialisation(m, kn, p_order, order, smooth)
  m = estimation(m = m, maxit = 20)
  #m = output()
  return(m)

}





